# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - testdata
  skip-files: []

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - goconst
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
  
  goimports:
    local-prefixes: github.com/codervisor/devlog/collector

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
