/**
 * Project Entity for database storage
 *
 * Simplified compared to WorkspaceEntity - no per-project storage configuration.
 * All projects share the same centralized database configuration.
 */

import 'reflect-metadata';
import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from 'typeorm';
import type { Project } from '../types/index.js';
import { getTimestampType, TimestampColumn } from './decorators.js';

@Entity('devlog_projects')
export class ProjectEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'varchar', length: 255, unique: true })
  name!: string;

  @Column({ type: 'text', nullable: true })
  description?: string;

  @CreateDateColumn({
    type: getTimestampType(),
    name: 'created_at',
  })
  createdAt!: Date;

  @TimestampColumn({ name: 'last_accessed_at' })
  lastAccessedAt!: Date;

  /**
   * Convert entity to ProjectMetadata type
   */
  toProjectMetadata(): Project {
    return {
      id: this.id,
      name: this.name,
      description: this.description,
      createdAt: this.createdAt,
      lastAccessedAt: this.lastAccessedAt,
    };
  }

  /**
   * Create entity from ProjectMetadata
   */
  static fromProjectData(
    project: Omit<Project, 'id' | 'createdAt' | 'lastAccessedAt'>,
  ): ProjectEntity {
    const entity = new ProjectEntity();
    // id will be auto-generated by the database
    entity.name = project.name;
    entity.description = project.description;
    entity.lastAccessedAt = new Date();
    return entity;
  }

  /**
   * Update entity with partial project data
   */
  updateFromProjectData(updates: Partial<Project>): void {
    if (updates.name !== undefined) this.name = updates.name;
    if (updates.description !== undefined) this.description = updates.description;
    this.lastAccessedAt = new Date();
  }
}
