openapi: 3.0.3
info:
  title: Devlog Hierarchy API
  description: |
    API endpoints for managing the 5-level hierarchy in the AI Agent Observability Platform:
    - Projects (Git repositories)
    - Machines (Development environments)
    - Workspaces (VS Code windows)
    - ChatSessions (AI conversations)
    - AgentEvents (Time-series events)
    
    This API supports real-time event streaming, hierarchy navigation, and advanced filtering.
  version: 1.0.0
  contact:
    name: Codervisor Team
    email: tikazyq@163.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3200/api
    description: Development server
  - url: https://devlog.codervisor.com/api
    description: Production server

tags:
  - name: Machines
    description: Development environment management
  - name: Workspaces
    description: VS Code workspace operations
  - name: Projects
    description: Project hierarchy and events
  - name: Chat Sessions
    description: AI conversation session management
  - name: Events
    description: Agent event ingestion and streaming
  - name: Health
    description: Service health checks

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      description: Check if the API is running and healthy
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]

  /machines:
    get:
      tags: [Machines]
      summary: List all machines
      description: Returns all machines ordered by last seen time
      operationId: listMachines
      responses:
        '200':
          description: List of machines with workspace counts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MachineWithCounts'

    post:
      tags: [Machines]
      summary: Create or update machine
      description: Upserts a machine based on machineId
      operationId: upsertMachine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MachineCreateInput'
      responses:
        '200':
          description: Machine created or updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'

  /machines/{id}:
    get:
      tags: [Machines]
      summary: Get machine by ID
      operationId: getMachineById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Machine details with workspaces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineWithWorkspaces'

  /workspaces:
    post:
      tags: [Workspaces]
      summary: Create or update workspace
      operationId: upsertWorkspace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceCreateInput'
      responses:
        '200':
          description: Workspace created or updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'

  /workspaces/{workspaceId}:
    get:
      tags: [Workspaces]
      summary: Get workspace by VS Code ID
      operationId: getWorkspaceById
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workspace with context and sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspace:
                    $ref: '#/components/schemas/WorkspaceWithDetails'
                  context:
                    $ref: '#/components/schemas/WorkspaceContext'

  /projects/{id}/hierarchy:
    get:
      tags: [Projects]
      summary: Get project hierarchy tree
      operationId: getProjectHierarchy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Complete project hierarchy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectHierarchy'

  /projects/{id}/events:
    get:
      tags: [Projects]
      summary: Get project events with filters
      operationId: getProjectEvents
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: machineId
          in: query
          schema:
            type: integer
        - name: workspaceId
          in: query
          schema:
            type: integer
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
        - name: eventType
          in: query
          schema:
            type: string
        - name: agentId
          in: query
          schema:
            type: string
        - name: severity
          in: query
          schema:
            type: string
            enum: [info, warning, error]
        - name: limit
          in: query
          schema:
            type: integer
            maximum: 1000
            default: 100
      responses:
        '200':
          description: Filtered events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/AgentEvent'
                  count:
                    type: integer
                  filters:
                    type: object

  /chat-sessions:
    post:
      tags: [Chat Sessions]
      summary: Create or update chat session
      operationId: upsertChatSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatSessionCreateInput'
      responses:
        '200':
          description: Session created or updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSession'

  /chat-sessions/{sessionId}/events:
    get:
      tags: [Chat Sessions]
      summary: Get session events
      operationId: getSessionEvents
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session events
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/AgentEvent'
                  count:
                    type: integer

  /events/batch:
    post:
      tags: [Events]
      summary: Batch create agent events
      description: Maximum 1000 events per request
      operationId: batchCreateEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              maxItems: 1000
              items:
                $ref: '#/components/schemas/AgentEventCreateInput'
      responses:
        '201':
          description: Events created
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    type: integer
                  requested:
                    type: integer

  /events/stream:
    get:
      tags: [Events]
      summary: Real-time event stream (SSE)
      description: Server-Sent Events endpoint for real-time updates
      operationId: streamEvents
      parameters:
        - name: projectId
          in: query
          schema:
            type: integer
        - name: machineId
          in: query
          schema:
            type: integer
        - name: workspaceId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Event stream
          content:
            text/event-stream:
              schema:
                type: string

components:
  schemas:
    Machine:
      type: object
      properties:
        id:
          type: integer
        machineId:
          type: string
        hostname:
          type: string
        username:
          type: string
        osType:
          type: string
          enum: [darwin, linux, windows]
        osVersion:
          type: string
        machineType:
          type: string
          enum: [local, remote, cloud, ci]
        ipAddress:
          type: string
        metadata:
          type: object
        createdAt:
          type: string
          format: date-time
        lastSeenAt:
          type: string
          format: date-time

    MachineCreateInput:
      type: object
      required: [machineId, hostname, username, osType, machineType]
      properties:
        machineId:
          type: string
        hostname:
          type: string
        username:
          type: string
        osType:
          type: string
          enum: [darwin, linux, windows]
        osVersion:
          type: string
        machineType:
          type: string
          enum: [local, remote, cloud, ci]
        ipAddress:
          type: string
        metadata:
          type: object

    MachineWithCounts:
      allOf:
        - $ref: '#/components/schemas/Machine'
        - type: object
          properties:
            _count:
              type: object
              properties:
                workspaces:
                  type: integer

    MachineWithWorkspaces:
      allOf:
        - $ref: '#/components/schemas/Machine'
        - type: object
          properties:
            workspaces:
              type: array

    Workspace:
      type: object
      properties:
        id:
          type: integer
        projectId:
          type: integer
        machineId:
          type: integer
        workspaceId:
          type: string
        workspacePath:
          type: string
        workspaceType:
          type: string
          enum: [folder, multi-root]
        branch:
          type: string
        commit:
          type: string
        createdAt:
          type: string
          format: date-time
        lastSeenAt:
          type: string
          format: date-time

    WorkspaceCreateInput:
      type: object
      required: [projectId, machineId, workspaceId, workspacePath, workspaceType]
      properties:
        projectId:
          type: integer
        machineId:
          type: integer
        workspaceId:
          type: string
        workspacePath:
          type: string
        workspaceType:
          type: string
          enum: [folder, multi-root]
        branch:
          type: string
        commit:
          type: string

    WorkspaceWithDetails:
      allOf:
        - $ref: '#/components/schemas/Workspace'
        - type: object
          properties:
            project:
              type: object
            machine:
              type: object
            chatSessions:
              type: array

    WorkspaceContext:
      type: object
      properties:
        projectId:
          type: integer
        machineId:
          type: integer
        workspaceId:
          type: integer
        projectName:
          type: string
        machineName:
          type: string

    Project:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fullName:
          type: string
        repoUrl:
          type: string
        repoOwner:
          type: string
        repoName:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProjectHierarchy:
      type: object
      properties:
        project:
          $ref: '#/components/schemas/Project'
        machines:
          type: array
          items:
            type: object
            properties:
              machine:
                $ref: '#/components/schemas/Machine'
              workspaces:
                type: array

    ChatSession:
      type: object
      properties:
        id:
          type: integer
        sessionId:
          type: string
          format: uuid
        workspaceId:
          type: integer
        agentType:
          type: string
        modelId:
          type: string
        startedAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
        messageCount:
          type: integer
        totalTokens:
          type: integer
        createdAt:
          type: string
          format: date-time

    ChatSessionCreateInput:
      type: object
      required: [sessionId, workspaceId, agentType, startedAt]
      properties:
        sessionId:
          type: string
          format: uuid
        workspaceId:
          type: integer
        agentType:
          type: string
        modelId:
          type: string
        startedAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
        messageCount:
          type: integer
        totalTokens:
          type: integer

    AgentEvent:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        eventType:
          type: string
        agentId:
          type: string
        agentVersion:
          type: string
        sessionId:
          type: string
        projectId:
          type: integer
        context:
          type: object
        data:
          type: object
        metrics:
          type: object
        parentEventId:
          type: string
        relatedEventIds:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        severity:
          type: string
          enum: [info, warning, error]
        createdAt:
          type: string
          format: date-time

    AgentEventCreateInput:
      type: object
      required: [timestamp, eventType, agentId, agentVersion, sessionId, projectId]
      properties:
        timestamp:
          type: string
          format: date-time
        eventType:
          type: string
        agentId:
          type: string
        agentVersion:
          type: string
        sessionId:
          type: string
          format: uuid
        projectId:
          type: integer
        context:
          type: object
        data:
          type: object
        metrics:
          type: object
        parentEventId:
          type: string
        relatedEventIds:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        severity:
          type: string
          enum: [info, warning, error]
